### ISSUE TITLE
Marker at the wrong place or text output at wrong place.

### ISSUE THREAD

**Issue by tmikaeld** [pepri/wizdler#6] opened 2013-07-29 13:54 UTC
Hi,

Using the latest Chrome, the text is written a few characters to the left of where i put the marker.

**Comment by pepri** [comment] 2013-07-30 07:57
Tested on both "30.0.1580.0 canary" and "28.0.1500.72 m" on Windows. Cannot reproduce.

**Comment by tmikaeld** [comment] 2013-07-30 08:03
I tried in windows, can confirm that it works fine there, the problem seems to be OS X only.

**Comment by pepri** [comment] 2013-07-30 08:19
Ok, I do not have OSX, so I cannot test it.

Please, try this page, whether the cursor is in the right position on this page: http://ace.c9.io/#nav=about
If it is, I will update the ACE editor to the newest version.

**Comment by tmikaeld** [comment] 2013-07-30 08:22
Yes, in that version it is in the right position.

Thanks for looking into this!

**Comment by pepri** [comment] 2013-08-01 13:10
I have updated the Wizdler to use the latest ACE editor. It is now available in the Web Store. Please update the extension to version 1.5 and check whether the problem still exists.

**Comment by tmikaeld** [comment] 2013-08-01 13:28
The problem still exists, it's really odd..

I'm sending you a video of it in a private message.

EDIT: How do i send a private message? :-S

**Comment by pepri** [comment] 2013-08-01 14:48
I am afraid I won't be able to fix this issue. Maybe it is caused by the hidden gutter. Or because of the tab characters (but they are converted to spaces, so thet should not cause a problem)?

If you turn off the "Show Gutter" option in the [kitchen sink](http://ace.c9.io/build/kitchen-sink.html), is the cursor in right position? I will try to get a Mac next week to check it out.

**Comment by tmikaeld** [comment] 2013-08-01 18:52
I tried to enable every option in the "kitchen sink" and there is no problem with the marker position there at all.
But it still doesn't work in Wizdler. I will take some time going through your source code during the weekend and see if i can find something.

About OS X - I think the best option would be to get a license for OS X Mountain Lion via iTunes, it's like 15€ so very cheap.

Then follow this guide: http://lifehacker.com/5938332/how-to-run-mac-os-x-on-any-windows-pc-using-virtualbox

This way you can test and edit settings, and you can easily do roll-backs if something breaks and you can easily transfer files or even install XAMPP locally and try with that.

**Comment by pepri** [comment] 2013-08-05 08:13
Fixed in version 1.7, available in Web Store.

**Closed as completed by pepri** 2013-08-05 08:13 UTC

**Comment by tmikaeld** [comment] 2013-08-05 08:28
Superb, thank you!
