### ISSUE TITLE
Object [object Object] has no method 'clone'

### ISSUE THREAD

**Issue by jmshinn** [pepri/wizdler#9] opened 2013-12-16 22:47 UTC
I'm getting this error when attempting to use a particular function exposed by a wsdl.  It's not all functions, just some of them.

It looks like this is related to generating the example request, specifically:
https://github.com/pepri/wizdler/blob/46164ede11866e674a2bea5a0c92ca2a8862e5e9/wizdler/scripts/xmlSampleGenerator.js
Line 148

The wsdl is the FedEx ShipService wsdl.

**Comment by jmshinn** [comment] 2013-12-16 22:49
GitHub won't let me attach the wsdl, and when I tried to copy/paste, it said it was too long.  If you'd like me to get it to you some other way let me know.

**Comment by pepri** [comment] 2014-01-08 22:57
Sorry, I have been too busy last month. Please send me the WSDL to peto.prikryl@gmail.com and I will look into it when possible.

**Comment by jmshinn** [comment] 2014-01-09 14:03
No problem, I appreciate whatever time you have to help me, for this I just had to go back to my previous, inferior methods of troubleshooting rather than using your awesome plugin.

Sent you an email with the WSDL.

**Comment by pepri** [comment] 2014-01-14 06:30
Thanks for the WSDL. The issue is fixed in the version 1.13 and is available on the web store.

**Closed as completed by pepri** 2014-01-14 06:30 UTC

**Comment by jmshinn** [comment] 2014-01-14 21:02
Looks like it's working for me now, thanks much!
